// @ts-check
const path = require("node:path");
const { defineConfig } = require("eslint/config");
const expoConfig = require("eslint-config-expo/flat");
const tailwind = require("eslint-plugin-tailwindcss");

module.exports = defineConfig([
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "android/**",
      "ios/**",
      ".expo/**",
      // Auto-generated by `npm run gen:api-types` (openapi-typescript) — see
      // its own header comment ("Do not make direct changes to the file").
      "src/api/schema.gen.ts",
    ],
  },
  expoConfig,
  ...tailwind.configs["flat/recommended"],
  {
    // eslint-config-expo's base globals cover `module`/`require` (CJS) but
    // not `__dirname` — only `metro.config.js` gets the full Node global
    // set via its own override. This file needs `__dirname` for the
    // absolute tailwind config path above, so it gets the same treatment.
    files: ["eslint.config.js"],
    languageOptions: {
      globals: { __dirname: "readonly" },
    },
  },
  {
    settings: {
      tailwindcss: {
        // NativeWind v4's `className` prop is the only place this app
        // writes Tailwind utility strings (no `clsx`/`cva` usage) — the
        // plugin's own default regex (`^class(Name)?$`) already covers it.
        //
        // Must be absolute: the plugin's tailwindcss-v3 loader takes
        // `path.dirname(config)` as the resolution root, and a relative
        // "./tailwind.config.js" dirnames down to just ".", which
        // `local-pkg`'s resolver fails to resolve `tailwindcss` from
        // (verified directly — absolute paths resolve fine, "." does not).
        config: path.join(__dirname, "tailwind.config.js"),
      },
    },
    rules: {
      // The whole point of adding this plugin: `tsc` type-checks a
      // `className="..."` string clean even when the class doesn't exist
      // (typo, wrong token, stale name), so a bad class only ever shows up
      // visually on a device. This is the one rule in this config that
      // catches that class of bug, so it stays an error rather than the
      // plugin's own default `warn`.
      // No `whitelist` needed here: verified (see the deliberate-typo test
      // in the setup report) that every real token — including the
      // "TRANSITIONAL" sand/cream/olive/terracotta aliases in
      // tailwind.config.js — resolves cleanly through the plugin's own
      // class-list build off that same config, while an invalid/typo'd
      // class is still correctly flagged.
      "tailwindcss/no-custom-classname": "error",
    },
  },
]);
