/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks Endpoint */
        get: operations["list_tasks_endpoint_api_tasks_get"];
        put?: never;
        /** Create Task Endpoint */
        post: operations["create_task_endpoint_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Task Endpoint */
        post: operations["complete_task_endpoint_api_tasks__task_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/drop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drop Task Endpoint */
        post: operations["drop_task_endpoint_api_tasks__task_id__drop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today Tasks Endpoint */
        get: operations["today_tasks_endpoint_api_tasks_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overdue Tasks Endpoint */
        get: operations["overdue_tasks_endpoint_api_tasks_overdue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time Blocks Endpoint */
        get: operations["time_blocks_endpoint_api_time_blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Time Start Endpoint */
        post: operations["time_start_endpoint_api_time_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Time Stop Endpoint */
        post: operations["time_stop_endpoint_api_time_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time Current Endpoint */
        get: operations["time_current_endpoint_api_time_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time Open Endpoint */
        get: operations["time_open_endpoint_api_time_open_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkin/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checkin Pending Endpoint */
        get: operations["checkin_pending_endpoint_api_checkin_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkin/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkin Reply Endpoint */
        post: operations["checkin_reply_endpoint_api_checkin_reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkin/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checkin Coverage Endpoint */
        get: operations["checkin_coverage_endpoint_api_checkin_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Endpoint */
        post: operations["capture_endpoint_api_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefing/morning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Briefing Morning Endpoint */
        get: operations["briefing_morning_endpoint_api_briefing_morning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefing/evening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Briefing Evening Endpoint */
        get: operations["briefing_evening_endpoint_api_briefing_evening_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budget Status Endpoint */
        get: operations["budget_status_endpoint_api_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Budget Set Endpoint */
        patch: operations["budget_set_endpoint_api_budget_patch"];
        trace?: never;
    };
    "/api/push/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push Register Endpoint
         * @description Register (or refresh) a device token for the not-yet-built push transport.
         *
         *     This endpoint only persists the token; it does not send anything.
         */
        post: operations["push_register_endpoint_api_push_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Agent Message Endpoint */
        post: operations["create_agent_message_endpoint_api_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/message/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Message Endpoint */
        get: operations["get_agent_message_endpoint_api_message__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Messages Endpoint */
        get: operations["list_agent_messages_endpoint_api_messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status Endpoint */
        get: operations["status_endpoint_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentMessageCreatedResponse
         * @description POST /api/message — 202 Accepted; the row has just been created.
         */
        AgentMessageCreatedResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
        };
        /** AgentMessageRequest */
        AgentMessageRequest: {
            /** Text */
            text: string;
        };
        /**
         * AgentMessageResponse
         * @description GET /api/message/{id} and /api/messages — full ``agent_messages`` row.
         *
         *     Deliberately NOT built with ``response_model_exclude_none``: ``reply``
         *     and ``error`` are mutually-exclusive-ish but both always present as keys
         *     (``null`` when not applicable) so the client can rely on a stable shape
         *     rather than checking for key existence. An asymmetric response shape
         *     from an optional branch has already caused one real bug in this file
         *     (see ``PendingCheckinResponse``) — not repeating that here.
         */
        AgentMessageResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Text */
            text: string;
            /** Reply */
            reply: string | null;
            /** Reply Lede */
            reply_lede: string | null;
            /** Reply Body */
            reply_body: string | null;
            /** Error */
            error: string | null;
            /** Complexity */
            complexity: string | null;
            /** Model */
            model: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Voice Violations */
            voice_violations: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * BriefingResponse
         * @description Shadow-briefing file read; both fields are None together when missing.
         */
        BriefingResponse: {
            /** Text */
            text: string | null;
            /** Date */
            date: string | null;
        };
        /**
         * BudgetResponse
         * @description Mirrors ``fennoc.budget.get_budget_status``.
         */
        BudgetResponse: {
            /** Limit */
            limit: number;
            /** Spent */
            spent: number;
            /** Remaining */
            remaining: number;
            /** Deferred */
            deferred: number;
            /** Quiet Hours */
            quiet_hours: boolean;
            /** Reset At */
            reset_at: string;
        };
        /** CaptureRequest */
        CaptureRequest: {
            /** Text */
            text: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /**
         * CaptureResponse
         * @description ``append_capture`` returns ``None`` for ``event_id`` on idempotent dup.
         */
        CaptureResponse: {
            /** Ok */
            ok: boolean;
            /** Event Id */
            event_id: string | null;
        };
        /** CheckinCoverageResponse */
        CheckinCoverageResponse: {
            /** Answered */
            answered: number;
            /** Total */
            total: number;
        };
        /** CheckinReplyRequest */
        CheckinReplyRequest: {
            /** Text */
            text: string;
            /** Question Type */
            question_type?: string | null;
        };
        /** CheckinReplyResponse */
        CheckinReplyResponse: {
            /** Ok */
            ok: boolean;
            /** Ack */
            ack: string;
        };
        /** CreateTaskRequest */
        CreateTaskRequest: {
            /** Title */
            title: string;
            /** Project */
            project?: string | null;
            /** Priority */
            priority?: number | null;
            /** Due Date */
            due_date?: string | null;
            /** Labels */
            labels?: string[] | null;
        };
        /**
         * CreateTaskResponse
         * @description ``create_task`` returns ``None`` for ``task_id`` on idempotency-key duplicate.
         */
        CreateTaskResponse: {
            /** Task Id */
            task_id: string | null;
            /** Title */
            title: string;
        };
        /**
         * CurrentActivityResponse
         * @description GET /api/time/current — cursor-backed, set only by fennoc.checkins.
         *
         *     Discriminated on ``active``; when True the writer (``_set_current_activity``)
         *     always sets all three optional fields together, but they're modelled as
         *     optional since the cursor is free-form JSON. Route uses
         *     response_model_exclude_none so the ``active: False`` branch stays the
         *     original bare ``{"active": false}`` shape.
         */
        CurrentActivityResponse: {
            /** Active */
            active: boolean;
            /** Category */
            category?: string | null;
            /** Label */
            label?: string | null;
            /** Started At */
            started_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OkResponse
         * @description Shared shape for the task complete/drop endpoints: ``{"ok": bool}``.
         */
        OkResponse: {
            /** Ok */
            ok: boolean;
        };
        /**
         * OpenTimerResponse
         * @description GET /api/time/open — the manual start/stop timer cursor.
         *
         *     Same discriminant pattern as CurrentActivityResponse; kept as a
         *     separate model because it's a semantically distinct cursor
         *     (``time_open_block`` vs ``current_activity``), matching the client's
         *     separate ``OpenTimer`` / ``CheckinCurrent`` types.
         */
        OpenTimerResponse: {
            /** Active */
            active: boolean;
            /** Started At */
            started_at?: string | null;
            /** Label */
            label?: string | null;
            /** Category */
            category?: string | null;
        };
        /**
         * PendingCheckinResponse
         * @description GET /api/checkin/pending — both branches always carry ``pending``.
         *
         *     This is the model for the bug this pass exists to prevent: the endpoint
         *     used to omit ``pending`` on the populated branch entirely. Route uses
         *     response_model_exclude_none so the empty branch stays the original bare
         *     ``{"pending": false}`` shape.
         */
        PendingCheckinResponse: {
            /** Pending */
            pending: boolean;
            /** Id */
            id?: number | null;
            /** Sent At */
            sent_at?: string | null;
            /** Question Type */
            question_type?: string | null;
            /** Question Text */
            question_text?: string | null;
        };
        /** PushRegisterRequest */
        PushRegisterRequest: {
            /** Token */
            token: string;
            /** Platform */
            platform: string;
            /** User */
            user?: string | null;
        };
        /**
         * PushRegisterResponse
         * @description Mirrors the ``DeviceToken`` fields echoed back by ``register_device_token``.
         */
        PushRegisterResponse: {
            /** Ok */
            ok: boolean;
            /** Token */
            token: string;
            /** Platform */
            platform: string;
            /** User */
            user: string;
            /** Last Seen At */
            last_seen_at: string;
        };
        /** SetBudgetRequest */
        SetBudgetRequest: {
            /** Limit */
            limit: number;
        };
        /**
         * StatusResponse
         * @description Mirrors the aggregate dict built by ``status_endpoint``.
         */
        StatusResponse: {
            /** Open */
            open: number;
            /** Completed */
            completed: number;
            /** Overdue */
            overdue: number;
            checkin_coverage: components["schemas"]["CheckinCoverageResponse"];
        };
        /**
         * TaskResponse
         * @description Mirrors ``fennoc.store.accessors.Task`` (table `tasks`, migration 006/007).
         */
        TaskResponse: {
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            /** Project */
            project: string;
            /** Priority */
            priority: number;
            /** Due Date */
            due_date: string | null;
            /** Labels */
            labels: string[];
            /** Status */
            status: string;
            /** Source */
            source: string;
            /** Source Ref */
            source_ref: string;
            /** Recurrence */
            recurrence: string | null;
            /** Recurrence Parent Id */
            recurrence_parent_id: string | null;
            /** Created At */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Updated At */
            updated_at: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * TimeActionResponse
         * @description Shared shape for /api/time/start and /api/time/stop.
         */
        TimeActionResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        };
        /**
         * TimeBlockResponse
         * @description Mirrors ``fennoc.store.accessors.TimeBlock`` (table `time_blocks`, migration 005).
         *
         *     ``metadata`` is a JSON string on the wire, not an object — matches the
         *     dataclass field and the pre-existing warning in the client's types.ts.
         */
        TimeBlockResponse: {
            /** Block Id */
            block_id: string;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string;
            /** Duration S */
            duration_s: number;
            /** Source */
            source: string;
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Confidence */
            confidence: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Metadata */
            metadata: string;
            /** Created At */
            created_at: string;
        };
        /** TimeStartRequest */
        TimeStartRequest: {
            /** Category */
            category: string;
            /** Label */
            label?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tasks_endpoint_api_tasks_get: {
        parameters: {
            query?: {
                status?: string;
                project?: string | null;
                priority?: number | null;
                due_before?: string | null;
                due_after?: string | null;
                source?: string | null;
                domain?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_endpoint_api_tasks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_task_endpoint_api_tasks__task_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drop_task_endpoint_api_tasks__task_id__drop_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    today_tasks_endpoint_api_tasks_today_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overdue_tasks_endpoint_api_tasks_overdue_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_blocks_endpoint_api_time_blocks_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeBlockResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_start_endpoint_api_time_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_stop_endpoint_api_time_stop_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_current_endpoint_api_time_current_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_open_endpoint_api_time_open_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenTimerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkin_pending_endpoint_api_checkin_pending_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingCheckinResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkin_reply_endpoint_api_checkin_reply_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckinReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinReplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkin_coverage_endpoint_api_checkin_coverage_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinCoverageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_endpoint_api_capture_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    briefing_morning_endpoint_api_briefing_morning_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    briefing_evening_endpoint_api_briefing_evening_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    budget_status_endpoint_api_budget_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    budget_set_endpoint_api_budget_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBudgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_register_endpoint_api_push_register_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_message_endpoint_api_message_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMessageCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_message_endpoint_api_message__message_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_messages_endpoint_api_messages_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMessageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_endpoint_api_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
