/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks Endpoint */
        get: operations["list_tasks_endpoint_api_tasks_get"];
        put?: never;
        /** Create Task Endpoint */
        post: operations["create_task_endpoint_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Task Endpoint */
        post: operations["complete_task_endpoint_api_tasks__task_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/drop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drop Task Endpoint */
        post: operations["drop_task_endpoint_api_tasks__task_id__drop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today Tasks Endpoint */
        get: operations["today_tasks_endpoint_api_tasks_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overdue Tasks Endpoint */
        get: operations["overdue_tasks_endpoint_api_tasks_overdue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time Blocks Endpoint */
        get: operations["time_blocks_endpoint_api_time_blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Time Start Endpoint */
        post: operations["time_start_endpoint_api_time_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Time Stop Endpoint */
        post: operations["time_stop_endpoint_api_time_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time Current Endpoint */
        get: operations["time_current_endpoint_api_time_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time Open Endpoint */
        get: operations["time_open_endpoint_api_time_open_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkin/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checkin Pending Endpoint */
        get: operations["checkin_pending_endpoint_api_checkin_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkin/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkin Reply Endpoint */
        post: operations["checkin_reply_endpoint_api_checkin_reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkin/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checkin Coverage Endpoint */
        get: operations["checkin_coverage_endpoint_api_checkin_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Endpoint */
        post: operations["capture_endpoint_api_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefing/morning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Briefing Morning Endpoint */
        get: operations["briefing_morning_endpoint_api_briefing_morning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefing/evening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Briefing Evening Endpoint */
        get: operations["briefing_evening_endpoint_api_briefing_evening_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budget Status Endpoint */
        get: operations["budget_status_endpoint_api_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Budget Set Endpoint */
        patch: operations["budget_set_endpoint_api_budget_patch"];
        trace?: never;
    };
    "/api/push/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push Register Endpoint
         * @description Register (or refresh) a device token for the not-yet-built push transport.
         *
         *     This endpoint only persists the token; it does not send anything.
         */
        post: operations["push_register_endpoint_api_push_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reminders Endpoint
         * @description Every open (not yet closed) reminder for *owner* -- fired-and-waiting
         *     or not-yet-due alike. The future ledger's SET DOWN group reads this same
         *     accessor (``list_open_set_down_items``).
         */
        get: operations["list_reminders_endpoint_api_reminders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reminder/{reminder_id}/done": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reminder Done Endpoint
         * @description Close a reminder as done -- the shade's (or a conversational) "done
         *     with that" action. Idempotent at the accessor level; the second call
         *     against an already-closed id still returns the (unchanged) row rather
         *     than erroring, since "mark it done" twice is not a conflict worth
         *     surfacing to a client that may have retried a flaky request.
         */
        post: operations["reminder_done_endpoint_api_reminder__reminder_id__done_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reminder/{reminder_id}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reminder Snooze Endpoint
         * @description Reschedule a fired-but-unanswered reminder -- reuses
         *     ``fennoc.reminders.parse_when``, the exact grammar
         *     ``fennoc_set_reminder`` uses at creation, so "snooze until 6" means the
         *     same thing in both places. A snooze into quiet hours is refused the same
         *     way creation is: one line, with the alternative, never silently pushed
         *     past it.
         */
        post: operations["reminder_snooze_endpoint_api_reminder__reminder_id__snooze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Image Endpoint
         * @description Accept an explicitly-attached image, extract everything from it once, discard it.
         *
         *     This endpoint IS the "explicit send" moment that
         *     ``fennoc.vision.client``'s EXPLICIT SEND ONLY rule depends on: the vision
         *     model is only ever called because a client (the app, on the user's own
         *     action of attaching a photo) POSTed bytes here. Nothing else in this
         *     codebase calls ``fennoc.vision.storage.process_image`` — no collector, no
         *     vault sync, no cron job.
         *
         *     The image is NOT stored. It is read into memory, validated, sent to the
         *     vision model exactly once (with an optional *question* answered in
         *     addition to the standard thorough extraction — see
         *     ``fennoc.vision.client.build_extraction_question``), and its bytes are
         *     discarded by ``process_image`` before this function returns, on every
         *     path including a failed vision call. Only the resulting
         *     ``extracted_text`` is persisted.
         *
         *     Only recognized image mime types are accepted
         *     (``fennoc.vision.storage.ALLOWED_MIME_TYPES``) — checked against the
         *     upload's declared ``Content-Type`` before the body is even read, so an
         *     obviously-wrong upload (a PDF, a video) is rejected without the bytes
         *     ever being pulled into memory. The byte-size ceiling
         *     (``fennoc.vision.client.MAX_IMAGE_BYTES``) is enforced by
         *     ``process_image`` itself before the vision model is called.
         *
         *     **The read also joins the thread (INT-046).** Before this, a successful
         *     extraction landed in the ``images`` table and was returned to the app —
         *     both of which the agent's own ``hydrate_history()`` never reads — so the
         *     assistant had no memory of a photo it had just processed. Confirmed in
         *     production 2026-08-01: three extractions, minutes apart, while Fennoc
         *     truthfully denied ever seeing an image. ``create_image_turn`` (see its
         *     own docstring) writes the same shape INT-013 established for check-ins —
         *     a ``kind='user'`` row, already ``done`` — so the next turn on the thread
         *     sees the read without anyone having to ask again. The ``images`` row
         *     keeps being written exactly as before; it remains what
         *     ``fennoc_recall_image`` reads from, it just stops being the *only* place
         *     the read exists.
         */
        post: operations["upload_image_endpoint_api_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Image Endpoint
         * @description Undo, for a shot that already finished uploading — makes it real.
         *
         *     ``POST /api/image`` never retains the bytes (see that endpoint's own
         *     docstring), but the ``extracted_text`` row it inserts survives past the
         *     request — and that row IS the sensitive part: a full transcription of
         *     whatever was photographed. The app's 10s Undo (Step 11 of the design
         *     handoff, "Undo lives on the sent message for 10s") only hides the
         *     message client-side for an already-sent shot unless something also
         *     deletes this row — this endpoint is that something. A held/offline shot
         *     doesn't need it: the outbox item is removed and the local file deleted
         *     before any request is ever made (see ``fennoc-app``'s
         *     ``cancelHeldUploadsForBatch``), so there is no server row to clean up in
         *     that case.
         *
         *     Idempotent by design: always 204, never 404, whether or not
         *     *image_id* matched a row. A genuinely unknown id at every OTHER
         *     endpoint in this file (``/api/tasks/{id}/complete``, `.../drop`) is a
         *     404, because there the id came from a listing the client had just read
         *     — a miss means the client is confused about what exists, which is worth
         *     surfacing. Undo is a different shape of call: the client fires it once
         *     per shot in the batch with no read beforehand to confirm the row is
         *     still there, and it can legitimately fire twice for the same id (a
         *     dropped response retried, or two rapid Undo taps racing each other). In
         *     both of those the row is equally gone either way — "was already
         *     deleted" and "I just deleted it" are the same postcondition for a
         *     caller that only ever wanted to be sure a delete happened, so there is
         *     nothing for a distinct status code to tell it. Returning 404 on a
         *     replay would force the client to treat its OWN successful undo as an
         *     error to swallow, which is a worse design than just being idempotent.
         *
         *     Tenancy note: this endpoint does NOT filter by ``images.user`` before
         *     deleting, matching ``get_image``/``fennoc_recall_image`` (the existing
         *     read path), which also take an id with no user scoping. That is not a
         *     deliberate scoping decision made here — it's because there is no
         *     concept of "the requesting user" flowing through this request at all.
         *     ``verify_auth`` checks a single shared bearer token
         *     (``FENNOC_API_TOKEN``) against every caller; nothing about a valid
         *     request tells this handler who sent it, the way `body.user` does for
         *     ``/api/push/register``. This is a real gap for a hypothetically
         *     multi-tenant deployment (one token holder could delete another
         *     tenant's image row by guessing/observing its id), but it is not a new
         *     one this endpoint introduces — it is the same shape as every other
         *     unscoped-by-user read/write already in this file, and inventing a
         *     scoping scheme just for this one DELETE would be false safety: the GET
         *     side of the same row is already unscoped.
         *
         *     **INT-042 commit 2 extends this.** A routed image whose route created a
         *     task (the obligation route — see ``fennoc.capture.routing``) records
         *     that fact in ``images.route_effect``. Deleting the image now also drops
         *     the task it created, before deleting the row — so the photo's Undo
         *     undoes the route's action too (hard constraint: "nothing acts without
         *     telling you" implies its corollary, "nothing an Undo can't also
         *     undo"). Looked up before the row is gone, since ``get_image`` after
         *     ``delete_image`` would find nothing.
         */
        delete: operations["delete_image_endpoint_api_image__image_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Agent Message Endpoint */
        post: operations["create_agent_message_endpoint_api_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/message/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Message Endpoint */
        get: operations["get_agent_message_endpoint_api_message__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Messages Endpoint */
        get: operations["list_agent_messages_endpoint_api_messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Thread Endpoint
         * @description The durable thread (INT-057): a few days live, older days collapsed
         *     to one deterministic line each, day-expansion via repeatable
         *     ``?expand=YYYY-MM-DD``.
         *
         *     ``days`` is ordered oldest -> newest (today last), covering the live
         *     window (today + the 2 prior days, always present even with zero turns
         *     -- 18a: "you land at today") plus any older day that holds at least one
         *     turn, back to a ~30-day cap. Turn shape matches ``GET /api/messages``
         *     items exactly (both go through ``_agent_message_to_response``) so a
         *     client renders either source identically.
         */
        get: operations["get_thread_endpoint_api_thread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/resolve-overnight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Overnight Endpoint
         * @description The overnight-timer resolution (step 18a): done / keep / bin.
         *
         *     See ``fennoc.thread.resolve_overnight`` for what each action does --
         *     this endpoint is only the HTTP mapping (``OvernightResolutionError`` ->
         *     the status code it already carries).
         */
        post: operations["resolve_overnight_endpoint_api_time_resolve_overnight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status Endpoint */
        get: operations["status_endpoint_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentMessageCreatedResponse
         * @description POST /api/message — 202 Accepted; the row has just been created.
         */
        AgentMessageCreatedResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
        };
        /** AgentMessageRequest */
        AgentMessageRequest: {
            /** Text */
            text: string;
        };
        /**
         * AgentMessageResponse
         * @description GET /api/message/{id} and /api/messages — full ``agent_messages`` row.
         *
         *     Deliberately NOT built with ``response_model_exclude_none``: ``reply``
         *     and ``error`` are mutually-exclusive-ish but both always present as keys
         *     (``null`` when not applicable) so the client can rely on a stable shape
         *     rather than checking for key existence. An asymmetric response shape
         *     from an optional branch has already caused one real bug in this file
         *     (see ``PendingCheckinResponse``) — not repeating that here.
         */
        AgentMessageResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Text */
            text: string | null;
            /** Reply */
            reply: string | null;
            /** Reply Lede */
            reply_lede: string | null;
            /** Reply Body */
            reply_body: string | null;
            /** Error */
            error: string | null;
            /** Complexity */
            complexity: string | null;
            /** Model */
            model: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Voice Violations */
            voice_violations: {
                [key: string]: unknown;
            }[] | null;
            /** Kind */
            kind: string;
            /** Trigger */
            trigger: string | null;
            /** Actions */
            actions: {
                [key: string]: unknown;
            }[] | null;
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[] | null;
        };
        /** Body_upload_image_endpoint_api_image_post */
        Body_upload_image_endpoint_api_image_post: {
            /** File */
            file: string;
            /** Question */
            question?: string | null;
        };
        /**
         * BriefingResponse
         * @description Shadow-briefing file read; both fields are None together when missing.
         */
        BriefingResponse: {
            /** Text */
            text: string | null;
            /** Date */
            date: string | null;
        };
        /**
         * BudgetResponse
         * @description Mirrors ``fennoc.budget.get_budget_status``.
         */
        BudgetResponse: {
            /** Limit */
            limit: number;
            /** Spent */
            spent: number;
            /** Remaining */
            remaining: number;
            /** Deferred */
            deferred: number;
            /** Quiet Hours */
            quiet_hours: boolean;
            /** Reset At */
            reset_at: string;
        };
        /** CaptureRequest */
        CaptureRequest: {
            /** Text */
            text: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /**
         * CaptureResponse
         * @description ``append_capture`` returns ``None`` for ``event_id`` on idempotent dup.
         */
        CaptureResponse: {
            /** Ok */
            ok: boolean;
            /** Event Id */
            event_id: string | null;
        };
        /** CheckinCoverageResponse */
        CheckinCoverageResponse: {
            /** Answered */
            answered: number;
            /** Total */
            total: number;
        };
        /** CheckinReplyRequest */
        CheckinReplyRequest: {
            /** Text */
            text: string;
            /** Question Type */
            question_type?: string | null;
        };
        /**
         * CheckinReplyResponse
         * @description POST /api/checkin/reply.
         *
         *     ``ok``/``ack`` are unchanged from before INT-013 — ``ack`` is still the
         *     deterministic parser's own text (a logged-summary or a follow-up
         *     question), returned synchronously so the client's immediate UI feedback
         *     is unaffected. ``message_id`` is new and additive: the reply is now also
         *     a turn in the thread, dispatched to the agent the same way
         *     POST /api/message is (see ``_agent_turn_worker``), and this is the id a
         *     client polls via GET /api/message/{id} — the same
         *     addAgentPending/resolveAgent pattern a normal message uses — to pick up
         *     Fennoc's in-context response once it resolves.
         */
        CheckinReplyResponse: {
            /** Ok */
            ok: boolean;
            /** Ack */
            ack: string;
            /** Message Id */
            message_id: string;
        };
        /** CreateTaskRequest */
        CreateTaskRequest: {
            /** Title */
            title: string;
            /** Project */
            project?: string | null;
            /** Priority */
            priority?: number | null;
            /** Due Date */
            due_date?: string | null;
            /** Labels */
            labels?: string[] | null;
        };
        /**
         * CreateTaskResponse
         * @description ``create_task`` returns ``None`` for ``task_id`` on idempotency-key duplicate.
         */
        CreateTaskResponse: {
            /** Task Id */
            task_id: string | null;
            /** Title */
            title: string;
        };
        /**
         * CurrentActivityResponse
         * @description GET /api/time/current — cursor-backed, set only by fennoc.checkins.
         *
         *     Discriminated on ``active``; when True the writer (``_set_current_activity``)
         *     always sets all three optional fields together, but they're modelled as
         *     optional since the cursor is free-form JSON. Route uses
         *     response_model_exclude_none so the ``active: False`` branch stays the
         *     original bare ``{"active": false}`` shape.
         */
        CurrentActivityResponse: {
            /** Active */
            active: boolean;
            /** Category */
            category?: string | null;
            /** Label */
            label?: string | null;
            /** Started At */
            started_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageUploadResponse
         * @description POST /api/image — mirrors ``fennoc.store.accessors.StoredImage``.
         *
         *     The image itself is never stored (see ``fennoc.vision.storage``) — it is
         *     sent to the vision model exactly once, in this request, and discarded.
         *     ``extracted_text`` is that one pass's result: a full transcription plus
         *     scene description. ``id`` is what a subsequent ``fennoc_recall_image``
         *     tool call (or a follow-up question in the same conversation) references
         *     to read that text back — the client never needs to re-upload the photo,
         *     because there is no second look to take.
         */
        ImageUploadResponse: {
            /** Id */
            id: string;
            /** Mime */
            mime: string;
            /** Byte Size */
            byte_size: number;
            /** Created At */
            created_at: string;
            /** Extracted Text */
            extracted_text: string;
            /** Caption */
            caption?: string | null;
        };
        /**
         * OkResponse
         * @description Shared shape for the task complete/drop endpoints: ``{"ok": bool}``.
         */
        OkResponse: {
            /** Ok */
            ok: boolean;
        };
        /**
         * OpenTimerCardResponse
         * @description The overnight-timer resolution card (step 18a) -- present on
         *     ``GET /api/thread`` only when an open time block has survived the
         *     06:30 America/Chicago boundary (``fennoc.thread.detect_overnight_timer``).
         */
        OpenTimerCardResponse: {
            /** Block Id */
            block_id: string;
            /** Label */
            label: string;
            /** Started At */
            started_at: string;
            /** Suggested Minutes */
            suggested_minutes: number;
        };
        /**
         * OpenTimerResponse
         * @description GET /api/time/open — the manual start/stop timer cursor.
         *
         *     Same discriminant pattern as CurrentActivityResponse; kept as a
         *     separate model because it's a semantically distinct cursor
         *     (``time_open_block`` vs ``current_activity``), matching the client's
         *     separate ``OpenTimer`` / ``CheckinCurrent`` types.
         */
        OpenTimerResponse: {
            /** Active */
            active: boolean;
            /** Started At */
            started_at?: string | null;
            /** Label */
            label?: string | null;
            /** Category */
            category?: string | null;
        };
        /**
         * PendingCheckinResponse
         * @description GET /api/checkin/pending — both branches always carry ``pending``.
         *
         *     This is the model for the bug this pass exists to prevent: the endpoint
         *     used to omit ``pending`` on the populated branch entirely. Route uses
         *     response_model_exclude_none so the empty branch stays the original bare
         *     ``{"pending": false}`` shape.
         */
        PendingCheckinResponse: {
            /** Pending */
            pending: boolean;
            /** Id */
            id?: number | null;
            /** Sent At */
            sent_at?: string | null;
            /** Question Type */
            question_type?: string | null;
            /** Question Text */
            question_text?: string | null;
        };
        /** PushRegisterRequest */
        PushRegisterRequest: {
            /** Token */
            token: string;
            /** Platform */
            platform: string;
            /** User */
            user?: string | null;
        };
        /**
         * PushRegisterResponse
         * @description Mirrors the ``DeviceToken`` fields echoed back by ``register_device_token``.
         */
        PushRegisterResponse: {
            /** Ok */
            ok: boolean;
            /** Token */
            token: string;
            /** Platform */
            platform: string;
            /** User */
            user: string;
            /** Last Seen At */
            last_seen_at: string;
        };
        /**
         * ReminderResponse
         * @description Mirrors ``fennoc.store.accessors.SetDownItem`` (table ``set_down_items``,
         *     migration 020). ``GET /api/reminders`` is the ledger's future SET DOWN
         *     group's read; this is the same shape a single reminder's create/done/
         *     snooze endpoints echo back.
         */
        ReminderResponse: {
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** Text */
            text: string;
            /** Condition Type */
            condition_type: string;
            /** Condition Value */
            condition_value: string;
            /** Source Turn Id */
            source_turn_id: string | null;
            /** Created At */
            created_at: string;
            /** Fired At */
            fired_at: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Closed How */
            closed_how: string | null;
            /** Snoozed To */
            snoozed_to: string | null;
        };
        /**
         * ResolveOvernightRequest
         * @description Body of ``POST /api/time/resolve-overnight`` (INT-057 commit 3).
         *
         *     ``minutes`` is the "given" half of "close the block with the given (or
         *     suggested) duration" -- omit it to use ``fennoc.thread.
         *     suggested_minutes``'s own code-derived number instead.
         */
        ResolveOvernightRequest: {
            /** Block Id */
            block_id: string;
            /** Action */
            action: string;
            /** Minutes */
            minutes?: number | null;
        };
        /**
         * ResolveOvernightResponse
         * @description ``POST /api/time/resolve-overnight`` -- mirrors
         *     ``fennoc.thread.resolve_overnight``'s return dict exactly; see that
         *     function's docstring for what each action does and does not touch.
         */
        ResolveOvernightResponse: {
            /** Ok */
            ok: boolean;
            /** Action */
            action: string;
            /** Block Id */
            block_id: string;
            /** Time Block Id */
            time_block_id?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Task Completed */
            task_completed?: string | null;
        };
        /** SetBudgetRequest */
        SetBudgetRequest: {
            /** Limit */
            limit: number;
        };
        /**
         * SnoozeReminderRequest
         * @description Body of ``POST /api/reminder/{id}/snooze`` -- reuses the commit-2
         *     when-grammar (``fennoc.reminders.parse_when``), not a second parser.
         */
        SnoozeReminderRequest: {
            /** Until */
            until: string;
        };
        /**
         * StatusResponse
         * @description Mirrors the aggregate dict built by ``status_endpoint``.
         */
        StatusResponse: {
            /** Open */
            open: number;
            /** Completed */
            completed: number;
            /** Overdue */
            overdue: number;
            checkin_coverage: components["schemas"]["CheckinCoverageResponse"];
        };
        /**
         * TaskResponse
         * @description Mirrors ``fennoc.store.accessors.Task`` (table `tasks`, migration 006/007).
         */
        TaskResponse: {
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            /** Project */
            project: string;
            /** Priority */
            priority: number;
            /** Due Date */
            due_date: string | null;
            /** Labels */
            labels: string[];
            /** Status */
            status: string;
            /** Source */
            source: string;
            /** Source Ref */
            source_ref: string;
            /** Recurrence */
            recurrence: string | null;
            /** Recurrence Parent Id */
            recurrence_parent_id: string | null;
            /** Created At */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Updated At */
            updated_at: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * ThreadDayResponse
         * @description One entry in ``GET /api/thread``'s ``days`` array (INT-057 commit 3).
         *
         *     ``turns`` carries full ``AgentMessageResponse``-shaped items for a
         *     ``"live"`` day, or an expanded (``?expand=YYYY-MM-DD``) ``"collapsed"``
         *     one -- otherwise empty. ``line`` is populated only for a ``"collapsed"``
         *     day (``fennoc.thread.day_summary_line``'s deterministic composition);
         *     ``None`` for ``"live"``, where the client renders turns directly instead
         *     of a summary line.
         */
        ThreadDayResponse: {
            /** Date */
            date: string;
            /** State */
            state: string;
            /** Turns */
            turns: components["schemas"]["AgentMessageResponse"][];
            /** Line */
            line: string | null;
            /** Turn Count */
            turn_count: number;
        };
        /**
         * ThreadResponse
         * @description ``GET /api/thread`` -- the durable thread the app renders (INT-057),
         *     replacing the client's today-only in-memory store as the render source
         *     (see the intent's own "What this amends").
         */
        ThreadResponse: {
            /** Days */
            days: components["schemas"]["ThreadDayResponse"][];
            open_timer: components["schemas"]["OpenTimerCardResponse"] | null;
        };
        /**
         * TimeActionResponse
         * @description Shared shape for /api/time/start and /api/time/stop.
         */
        TimeActionResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        };
        /**
         * TimeBlockResponse
         * @description Mirrors ``fennoc.store.accessors.TimeBlock`` (table `time_blocks`, migration 005).
         *
         *     ``metadata`` is a JSON string on the wire, not an object — matches the
         *     dataclass field and the pre-existing warning in the client's types.ts.
         */
        TimeBlockResponse: {
            /** Block Id */
            block_id: string;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string;
            /** Duration S */
            duration_s: number;
            /** Source */
            source: string;
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Confidence */
            confidence: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Metadata */
            metadata: string;
            /** Created At */
            created_at: string;
        };
        /** TimeStartRequest */
        TimeStartRequest: {
            /** Category */
            category: string;
            /** Label */
            label?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tasks_endpoint_api_tasks_get: {
        parameters: {
            query?: {
                status?: string;
                project?: string | null;
                priority?: number | null;
                due_before?: string | null;
                due_after?: string | null;
                source?: string | null;
                domain?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_endpoint_api_tasks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_task_endpoint_api_tasks__task_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drop_task_endpoint_api_tasks__task_id__drop_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    today_tasks_endpoint_api_tasks_today_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overdue_tasks_endpoint_api_tasks_overdue_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_blocks_endpoint_api_time_blocks_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeBlockResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_start_endpoint_api_time_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_stop_endpoint_api_time_stop_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_current_endpoint_api_time_current_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_open_endpoint_api_time_open_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenTimerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkin_pending_endpoint_api_checkin_pending_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingCheckinResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkin_reply_endpoint_api_checkin_reply_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckinReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinReplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkin_coverage_endpoint_api_checkin_coverage_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinCoverageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_endpoint_api_capture_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    briefing_morning_endpoint_api_briefing_morning_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    briefing_evening_endpoint_api_briefing_evening_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    budget_status_endpoint_api_budget_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    budget_set_endpoint_api_budget_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBudgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_register_endpoint_api_push_register_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reminders_endpoint_api_reminders_get: {
        parameters: {
            query?: {
                owner?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reminder_done_endpoint_api_reminder__reminder_id__done_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                reminder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reminder_snooze_endpoint_api_reminder__reminder_id__snooze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                reminder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnoozeReminderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_endpoint_api_image_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_endpoint_api_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_endpoint_api_image__image_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_message_endpoint_api_message_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMessageCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_message_endpoint_api_message__message_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_messages_endpoint_api_messages_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMessageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_endpoint_api_thread_get: {
        parameters: {
            query?: {
                expand?: string[];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_overnight_endpoint_api_time_resolve_overnight_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveOvernightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveOvernightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_endpoint_api_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
