/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks Endpoint */
        get: operations["list_tasks_endpoint_api_tasks_get"];
        put?: never;
        /** Create Task Endpoint */
        post: operations["create_task_endpoint_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Task Endpoint */
        post: operations["complete_task_endpoint_api_tasks__task_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/drop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drop Task Endpoint */
        post: operations["drop_task_endpoint_api_tasks__task_id__drop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today Tasks Endpoint */
        get: operations["today_tasks_endpoint_api_tasks_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overdue Tasks Endpoint */
        get: operations["overdue_tasks_endpoint_api_tasks_overdue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time Blocks Endpoint */
        get: operations["time_blocks_endpoint_api_time_blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Time Start Endpoint */
        post: operations["time_start_endpoint_api_time_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Time Stop Endpoint */
        post: operations["time_stop_endpoint_api_time_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time Current Endpoint */
        get: operations["time_current_endpoint_api_time_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time Open Endpoint */
        get: operations["time_open_endpoint_api_time_open_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkin/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checkin Pending Endpoint */
        get: operations["checkin_pending_endpoint_api_checkin_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkin/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkin Reply Endpoint */
        post: operations["checkin_reply_endpoint_api_checkin_reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checkin/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checkin Coverage Endpoint */
        get: operations["checkin_coverage_endpoint_api_checkin_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Endpoint */
        post: operations["capture_endpoint_api_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefing/morning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Briefing Morning Endpoint */
        get: operations["briefing_morning_endpoint_api_briefing_morning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefing/evening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Briefing Evening Endpoint */
        get: operations["briefing_evening_endpoint_api_briefing_evening_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budget Status Endpoint */
        get: operations["budget_status_endpoint_api_budget_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Budget Set Endpoint */
        patch: operations["budget_set_endpoint_api_budget_patch"];
        trace?: never;
    };
    "/api/push/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push Register Endpoint
         * @description Register (or refresh) a device token for the not-yet-built push transport.
         *
         *     This endpoint only persists the token; it does not send anything.
         */
        post: operations["push_register_endpoint_api_push_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Image Endpoint
         * @description Accept an explicitly-attached image, extract everything from it once, discard it.
         *
         *     This endpoint IS the "explicit send" moment that
         *     ``fennoc.vision.client``'s EXPLICIT SEND ONLY rule depends on: the vision
         *     model is only ever called because a client (the app, on the user's own
         *     action of attaching a photo) POSTed bytes here. Nothing else in this
         *     codebase calls ``fennoc.vision.storage.process_image`` — no collector, no
         *     vault sync, no cron job.
         *
         *     The image is NOT stored. It is read into memory, validated, sent to the
         *     vision model exactly once (with an optional *question* answered in
         *     addition to the standard thorough extraction — see
         *     ``fennoc.vision.client.build_extraction_question``), and its bytes are
         *     discarded by ``process_image`` before this function returns, on every
         *     path including a failed vision call. Only the resulting
         *     ``extracted_text`` is persisted.
         *
         *     Only recognized image mime types are accepted
         *     (``fennoc.vision.storage.ALLOWED_MIME_TYPES``) — checked against the
         *     upload's declared ``Content-Type`` before the body is even read, so an
         *     obviously-wrong upload (a PDF, a video) is rejected without the bytes
         *     ever being pulled into memory. The byte-size ceiling
         *     (``fennoc.vision.client.MAX_IMAGE_BYTES``) is enforced by
         *     ``process_image`` itself before the vision model is called.
         */
        post: operations["upload_image_endpoint_api_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/image/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Image Endpoint
         * @description Undo, for a shot that already finished uploading — makes it real.
         *
         *     ``POST /api/image`` never retains the bytes (see that endpoint's own
         *     docstring), but the ``extracted_text`` row it inserts survives past the
         *     request — and that row IS the sensitive part: a full transcription of
         *     whatever was photographed. The app's 10s Undo (Step 11 of the design
         *     handoff, "Undo lives on the sent message for 10s") only hides the
         *     message client-side for an already-sent shot unless something also
         *     deletes this row — this endpoint is that something. A held/offline shot
         *     doesn't need it: the outbox item is removed and the local file deleted
         *     before any request is ever made (see ``fennoc-app``'s
         *     ``cancelHeldUploadsForBatch``), so there is no server row to clean up in
         *     that case.
         *
         *     Idempotent by design: always 204, never 404, whether or not
         *     *image_id* matched a row. A genuinely unknown id at every OTHER
         *     endpoint in this file (``/api/tasks/{id}/complete``, `.../drop`) is a
         *     404, because there the id came from a listing the client had just read
         *     — a miss means the client is confused about what exists, which is worth
         *     surfacing. Undo is a different shape of call: the client fires it once
         *     per shot in the batch with no read beforehand to confirm the row is
         *     still there, and it can legitimately fire twice for the same id (a
         *     dropped response retried, or two rapid Undo taps racing each other). In
         *     both of those the row is equally gone either way — "was already
         *     deleted" and "I just deleted it" are the same postcondition for a
         *     caller that only ever wanted to be sure a delete happened, so there is
         *     nothing for a distinct status code to tell it. Returning 404 on a
         *     replay would force the client to treat its OWN successful undo as an
         *     error to swallow, which is a worse design than just being idempotent.
         *
         *     Tenancy note: this endpoint does NOT filter by ``images.user`` before
         *     deleting, matching ``get_image``/``fennoc_recall_image`` (the existing
         *     read path), which also take an id with no user scoping. That is not a
         *     deliberate scoping decision made here — it's because there is no
         *     concept of "the requesting user" flowing through this request at all.
         *     ``verify_auth`` checks a single shared bearer token
         *     (``FENNOC_API_TOKEN``) against every caller; nothing about a valid
         *     request tells this handler who sent it, the way `body.user` does for
         *     ``/api/push/register``. This is a real gap for a hypothetically
         *     multi-tenant deployment (one token holder could delete another
         *     tenant's image row by guessing/observing its id), but it is not a new
         *     one this endpoint introduces — it is the same shape as every other
         *     unscoped-by-user read/write already in this file, and inventing a
         *     scoping scheme just for this one DELETE would be false safety: the GET
         *     side of the same row is already unscoped.
         */
        delete: operations["delete_image_endpoint_api_image__image_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Agent Message Endpoint */
        post: operations["create_agent_message_endpoint_api_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/message/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Message Endpoint */
        get: operations["get_agent_message_endpoint_api_message__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Messages Endpoint */
        get: operations["list_agent_messages_endpoint_api_messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status Endpoint */
        get: operations["status_endpoint_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentMessageCreatedResponse
         * @description POST /api/message — 202 Accepted; the row has just been created.
         */
        AgentMessageCreatedResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
        };
        /** AgentMessageRequest */
        AgentMessageRequest: {
            /** Text */
            text: string;
        };
        /**
         * AgentMessageResponse
         * @description GET /api/message/{id} and /api/messages — full ``agent_messages`` row.
         *
         *     Deliberately NOT built with ``response_model_exclude_none``: ``reply``
         *     and ``error`` are mutually-exclusive-ish but both always present as keys
         *     (``null`` when not applicable) so the client can rely on a stable shape
         *     rather than checking for key existence. An asymmetric response shape
         *     from an optional branch has already caused one real bug in this file
         *     (see ``PendingCheckinResponse``) — not repeating that here.
         */
        AgentMessageResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Text */
            text: string | null;
            /** Reply */
            reply: string | null;
            /** Reply Lede */
            reply_lede: string | null;
            /** Reply Body */
            reply_body: string | null;
            /** Error */
            error: string | null;
            /** Complexity */
            complexity: string | null;
            /** Model */
            model: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Voice Violations */
            voice_violations: {
                [key: string]: unknown;
            }[] | null;
            /** Kind */
            kind: string;
            /** Trigger */
            trigger: string | null;
        };
        /** Body_upload_image_endpoint_api_image_post */
        Body_upload_image_endpoint_api_image_post: {
            /** File */
            file: string;
            /** Question */
            question?: string | null;
        };
        /**
         * BriefingResponse
         * @description Shadow-briefing file read; both fields are None together when missing.
         */
        BriefingResponse: {
            /** Text */
            text: string | null;
            /** Date */
            date: string | null;
        };
        /**
         * BudgetResponse
         * @description Mirrors ``fennoc.budget.get_budget_status``.
         */
        BudgetResponse: {
            /** Limit */
            limit: number;
            /** Spent */
            spent: number;
            /** Remaining */
            remaining: number;
            /** Deferred */
            deferred: number;
            /** Quiet Hours */
            quiet_hours: boolean;
            /** Reset At */
            reset_at: string;
        };
        /** CaptureRequest */
        CaptureRequest: {
            /** Text */
            text: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /**
         * CaptureResponse
         * @description ``append_capture`` returns ``None`` for ``event_id`` on idempotent dup.
         */
        CaptureResponse: {
            /** Ok */
            ok: boolean;
            /** Event Id */
            event_id: string | null;
        };
        /** CheckinCoverageResponse */
        CheckinCoverageResponse: {
            /** Answered */
            answered: number;
            /** Total */
            total: number;
        };
        /** CheckinReplyRequest */
        CheckinReplyRequest: {
            /** Text */
            text: string;
            /** Question Type */
            question_type?: string | null;
        };
        /** CheckinReplyResponse */
        CheckinReplyResponse: {
            /** Ok */
            ok: boolean;
            /** Ack */
            ack: string;
        };
        /** CreateTaskRequest */
        CreateTaskRequest: {
            /** Title */
            title: string;
            /** Project */
            project?: string | null;
            /** Priority */
            priority?: number | null;
            /** Due Date */
            due_date?: string | null;
            /** Labels */
            labels?: string[] | null;
        };
        /**
         * CreateTaskResponse
         * @description ``create_task`` returns ``None`` for ``task_id`` on idempotency-key duplicate.
         */
        CreateTaskResponse: {
            /** Task Id */
            task_id: string | null;
            /** Title */
            title: string;
        };
        /**
         * CurrentActivityResponse
         * @description GET /api/time/current — cursor-backed, set only by fennoc.checkins.
         *
         *     Discriminated on ``active``; when True the writer (``_set_current_activity``)
         *     always sets all three optional fields together, but they're modelled as
         *     optional since the cursor is free-form JSON. Route uses
         *     response_model_exclude_none so the ``active: False`` branch stays the
         *     original bare ``{"active": false}`` shape.
         */
        CurrentActivityResponse: {
            /** Active */
            active: boolean;
            /** Category */
            category?: string | null;
            /** Label */
            label?: string | null;
            /** Started At */
            started_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageUploadResponse
         * @description POST /api/image — mirrors ``fennoc.store.accessors.StoredImage``.
         *
         *     The image itself is never stored (see ``fennoc.vision.storage``) — it is
         *     sent to the vision model exactly once, in this request, and discarded.
         *     ``extracted_text`` is that one pass's result: a full transcription plus
         *     scene description. ``id`` is what a subsequent ``fennoc_recall_image``
         *     tool call (or a follow-up question in the same conversation) references
         *     to read that text back — the client never needs to re-upload the photo,
         *     because there is no second look to take.
         */
        ImageUploadResponse: {
            /** Id */
            id: string;
            /** Mime */
            mime: string;
            /** Byte Size */
            byte_size: number;
            /** Created At */
            created_at: string;
            /** Extracted Text */
            extracted_text: string;
        };
        /**
         * OkResponse
         * @description Shared shape for the task complete/drop endpoints: ``{"ok": bool}``.
         */
        OkResponse: {
            /** Ok */
            ok: boolean;
        };
        /**
         * OpenTimerResponse
         * @description GET /api/time/open — the manual start/stop timer cursor.
         *
         *     Same discriminant pattern as CurrentActivityResponse; kept as a
         *     separate model because it's a semantically distinct cursor
         *     (``time_open_block`` vs ``current_activity``), matching the client's
         *     separate ``OpenTimer`` / ``CheckinCurrent`` types.
         */
        OpenTimerResponse: {
            /** Active */
            active: boolean;
            /** Started At */
            started_at?: string | null;
            /** Label */
            label?: string | null;
            /** Category */
            category?: string | null;
        };
        /**
         * PendingCheckinResponse
         * @description GET /api/checkin/pending — both branches always carry ``pending``.
         *
         *     This is the model for the bug this pass exists to prevent: the endpoint
         *     used to omit ``pending`` on the populated branch entirely. Route uses
         *     response_model_exclude_none so the empty branch stays the original bare
         *     ``{"pending": false}`` shape.
         */
        PendingCheckinResponse: {
            /** Pending */
            pending: boolean;
            /** Id */
            id?: number | null;
            /** Sent At */
            sent_at?: string | null;
            /** Question Type */
            question_type?: string | null;
            /** Question Text */
            question_text?: string | null;
        };
        /** PushRegisterRequest */
        PushRegisterRequest: {
            /** Token */
            token: string;
            /** Platform */
            platform: string;
            /** User */
            user?: string | null;
        };
        /**
         * PushRegisterResponse
         * @description Mirrors the ``DeviceToken`` fields echoed back by ``register_device_token``.
         */
        PushRegisterResponse: {
            /** Ok */
            ok: boolean;
            /** Token */
            token: string;
            /** Platform */
            platform: string;
            /** User */
            user: string;
            /** Last Seen At */
            last_seen_at: string;
        };
        /** SetBudgetRequest */
        SetBudgetRequest: {
            /** Limit */
            limit: number;
        };
        /**
         * StatusResponse
         * @description Mirrors the aggregate dict built by ``status_endpoint``.
         */
        StatusResponse: {
            /** Open */
            open: number;
            /** Completed */
            completed: number;
            /** Overdue */
            overdue: number;
            checkin_coverage: components["schemas"]["CheckinCoverageResponse"];
        };
        /**
         * TaskResponse
         * @description Mirrors ``fennoc.store.accessors.Task`` (table `tasks`, migration 006/007).
         */
        TaskResponse: {
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            /** Project */
            project: string;
            /** Priority */
            priority: number;
            /** Due Date */
            due_date: string | null;
            /** Labels */
            labels: string[];
            /** Status */
            status: string;
            /** Source */
            source: string;
            /** Source Ref */
            source_ref: string;
            /** Recurrence */
            recurrence: string | null;
            /** Recurrence Parent Id */
            recurrence_parent_id: string | null;
            /** Created At */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Updated At */
            updated_at: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * TimeActionResponse
         * @description Shared shape for /api/time/start and /api/time/stop.
         */
        TimeActionResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        };
        /**
         * TimeBlockResponse
         * @description Mirrors ``fennoc.store.accessors.TimeBlock`` (table `time_blocks`, migration 005).
         *
         *     ``metadata`` is a JSON string on the wire, not an object — matches the
         *     dataclass field and the pre-existing warning in the client's types.ts.
         */
        TimeBlockResponse: {
            /** Block Id */
            block_id: string;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at: string;
            /** Duration S */
            duration_s: number;
            /** Source */
            source: string;
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Confidence */
            confidence: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Metadata */
            metadata: string;
            /** Created At */
            created_at: string;
        };
        /** TimeStartRequest */
        TimeStartRequest: {
            /** Category */
            category: string;
            /** Label */
            label?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tasks_endpoint_api_tasks_get: {
        parameters: {
            query?: {
                status?: string;
                project?: string | null;
                priority?: number | null;
                due_before?: string | null;
                due_after?: string | null;
                source?: string | null;
                domain?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_endpoint_api_tasks_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_task_endpoint_api_tasks__task_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drop_task_endpoint_api_tasks__task_id__drop_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    today_tasks_endpoint_api_tasks_today_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overdue_tasks_endpoint_api_tasks_overdue_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_blocks_endpoint_api_time_blocks_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeBlockResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_start_endpoint_api_time_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_stop_endpoint_api_time_stop_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_current_endpoint_api_time_current_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    time_open_endpoint_api_time_open_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenTimerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkin_pending_endpoint_api_checkin_pending_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingCheckinResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkin_reply_endpoint_api_checkin_reply_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckinReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinReplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkin_coverage_endpoint_api_checkin_coverage_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinCoverageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_endpoint_api_capture_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    briefing_morning_endpoint_api_briefing_morning_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    briefing_evening_endpoint_api_briefing_evening_get: {
        parameters: {
            query?: {
                day?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    budget_status_endpoint_api_budget_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    budget_set_endpoint_api_budget_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBudgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_register_endpoint_api_push_register_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_endpoint_api_image_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_endpoint_api_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_endpoint_api_image__image_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_message_endpoint_api_message_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMessageCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_message_endpoint_api_message__message_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_messages_endpoint_api_messages_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMessageResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_endpoint_api_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
